### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by TheBricktop** [MateuszSiwiecki/opencvsharp-android#1]
Im very interested in building opencvsharp for android in mind.

**Comment by MateuszSiwiecki** [comment]
Yes it works, I know see, that I made this repo public. You can implement this source directly into your mobile app, but if you want use it for iOS you should provide opencv build for specify processor architecture.
This is oryginal wrapper for C# https://github.com/shimat/opencvsharp
This is oryginal wrapper for Xamarin.Adnroid, that I just modified for my own purpose https://github.com/Kawaian/OpenCvSharp
This is the film that I learned from how to implement opencv to Xamarin https://www.youtube.com/watch?v=xAUt7EBdNis&ab_channel=SamTech
I didn't touch any native function, but I modify some of AndroidCapture, so you could have some issue with it, I strongly recommend to download this solution from Kawaian repo.

**Comment by TheBricktop** [comment]
Is this version based on opencv 3 or 4 ? Cause im interested in kinfu functions.

**Comment by MateuszSiwiecki** [comment]
3.2

**Comment by TheBricktop** [comment]
Well that sucks,
kinfu seems to be implemented since v 4.0, any idea how to compile the recent opencv 4.5 the same way as Kawaiian did?

**Comment by MateuszSiwiecki** [comment]
First, you need create the version of opencv that will target your desire processor, then you need to create wrapper - see https://docs.microsoft.com/en-us/cpp/dotnet/how-to-wrap-native-class-for-use-by-csharp?view=msvc-160
At the end, you have to add references to your wrapper and make target dll as an embeded resource - follow the kawaian references for his projects.
